apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jlloc
spec:
  selector:
    matchLabels:
      app: jlloc
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
